[package]
name = "chromaprinter"
version = "0.1.0"
authors = ["Dmytro Lysai <d@emphased.net>"]
edition = "2018"

[dependencies]
fftw = "0.6"
num-traits = "0.2"
rand = "0.7"
samplerate = "0.2"

[dev-dependencies]
approx = "0.3"
byteorder = "1.3"